Convert config to build off Satellite 6.
In order for this to work, various environment variables need to be set
prior to running 'make'. For example, for RHEL7:

- VAGRANT_RHEL7_ORG="<orgid>"
- VAGRANT_RHEL7_KEY="<activationkey>'

It is recommended that this be done via a file that can be sourced,
especially if running 'build-all'.

Note that there is a difference between the way Satellite 5 and 6 deal
with unregistering systems.  The old 'satellite-deregister' script
deleted the system totally from Satellite 5, the new script for
Satellite 6 does not; it only deregisters them.  As a result deleting
the system profile entirely is currently a manual process.  Details are
in the README.md file.

Also note that the RHEL6 build currently installs the EPEL repo during
the build as some of the default packages come via EPEL and the new
Satellite does not currently have them available.

Additional notes:

- Updates the RHEL7 build to 7.7
- Build ISOs are still hosted on the old Satellite 5.8 server, until
  such time as we replace it with another "general repo" server
- Adds a "clean-tempfiles" target to the Makefile now that files are
  built from templates.  This also removes the output directory if it
  exists.

diff --git a/build/rhel7/files/satellite-deregister b/build/rhel7/files/satellite-deregister
--- a/build/rhel7/files/satellite-deregister
+++ b/build/rhel7/files/satellite-deregister
@@ -1,32 +1,16 @@
-#!/usr/bin/python
+#!/bin/bash
+subscription-manager remove --all
+subscription-manager unregister
+subscription-manager clean
+rpm -qa | grep -q 'katello-*'
+if [ "$?" -eq "0" ]; then
+  systemctl disable goferd
+  systemctl stop goferd
+  yum remove -y katello-*
+fi
+echo
+echo "Run the following command on the Satellite server to delete the system if required:"
+echo
+echo "# hammer host delete --name=$(uname -n)"
+echo
 
-import sys
-import os
-import traceback
-import xmlrpclib
-import ssl
-
-satellite_url = 'https://satellite.its.rmit.edu.au/rpc/api'
-systemid_file = '/etc/sysconfig/rhn/systemid'
-
-if (__name__ == '__main__'):
-    if (os.path.exists(systemid_file)):
-        try:
-            _create_unverified_https_context = ssl._create_unverified_context
-        except AttributeError:
-            pass
-        else:
-            ssl._create_default_https_context = _create_unverified_https_context
-        try:
-            client = xmlrpclib.Server(satellite_url)
-            with open(systemid_file, 'r') as fd:
-                systemid_data = fd.read()
-                rc = client.system.deleteSystem(systemid_data)
-                print('Successfully deregistered from Satellite.')
-        except:
-            print('Exception while deregistering.')
-            print traceback.format_exc()
-            sys.exit(1)
-        os.remove(systemid_file)
-    else:
-        print('The system is not registered with Satellite.')
diff --git a/build/rhel8/files/satellite-deregister b/build/rhel8/files/satellite-deregister
--- a/build/rhel8/files/satellite-deregister
+++ b/build/rhel8/files/satellite-deregister
@@ -1,5 +1,16 @@
 #!/bin/bash
-sudo /usr/sbin/subscription-manager remove --all
-sudo /usr/sbin/subscription-manager unregister
-sudo /usr/sbin/subscription-manager clean
+subscription-manager remove --all
+subscription-manager unregister
+subscription-manager clean
+rpm -qa | grep -q 'katello-*'
+if [ "$?" -eq "0" ]; then
+  systemctl disable goferd
+  systemctl stop goferd
+  yum remove -y katello-*
+fi
+echo
+echo "Run the following command on the Satellite server to delete the system if required:"
+echo
+echo "# hammer host delete --name=$(uname -n)"
+echo
 
